import Head from 'next/head'
import Link from 'next/link'

export default function Terms() {
  return (
    <>
      <Head>
        <title>Terms and Conditions | Novo Navis</title>
        <meta name="description" content="Novo Navis Terms and Conditions — please read before using our AI integration report service." />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <nav>
        <Link href="/" className="nav-logo">NOVO NAVIS</Link>
        <ul className="nav-links">
          <li><Link href="/">Home</Link></li>
          <li><Link href="/blog">Blog</Link></li>
          <li><Link href="/report">Get Your AI Blueprint</Link></li>
          <li><Link href="/about">About</Link></li>
        </ul>
      </nav>

      <div className="article-page">

        <h1>Terms and Conditions</h1>
        <p style={{color: '#8a95aa', fontSize: '0.85rem', marginBottom: '1.5rem'}}>
          Effective Date: April 24, 2026 · Novo Navis Aerospace Operations LLC
        </p>

        {/* FRIENDLY INTRO WITH REFUND PROMISE UP TOP */}
        <div style={{
          background: '#0a1a0a',
          border: '2px solid #4caf50',
          borderRadius: '8px',
          padding: '1.25rem 1.5rem',
          margin: '0 0 2rem 0'
        }}>
          <p style={{color: '#4caf50', fontSize: '1rem', fontWeight: 'bold', margin: '0 0 0.5rem 0'}}>
            ✓ 100% Money-Back Guarantee
          </p>
          <p style={{color: '#d0d8e8', fontSize: '0.92rem', lineHeight: '1.6', margin: 0}}>
            If you're not satisfied with your report for any reason, we'll refund you in full — no questions asked. Just email support@novonavis.com.
          </p>
        </div>

        <div className="article-body">

          <h2 style={{color: '#c8a96e', fontSize: '1.2rem', marginTop: '2rem', marginBottom: '0.8rem'}}>Agreement to Terms</h2>
          <p>By requesting, purchasing, or using any report or service provided by Novo Navis Aerospace Operations LLC ("Novo Navis," "we," "us," or "our"), you ("the Client," "you," or "your") agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not submit a report request or complete a purchase.</p>

          <h2 style={{color: '#c8a96e', fontSize: '1.2rem', marginTop: '2rem', marginBottom: '0.8rem'}}>Refund Policy</h2>
          <p>Novo Navis offers a full refund, no questions asked, if you are not satisfied with your report for any reason. Refund requests must be submitted within 72 hours of report delivery. To request a refund, email <a href="mailto:support@novonavis.com" style={{color: '#c8a96e'}}>support@novonavis.com</a>. Refunds are processed through Stripe and typically appear on your statement within 5 to 10 business days.</p>

          <h2 style={{color: '#c8a96e', fontSize: '1.2rem', marginTop: '2rem', marginBottom: '0.8rem'}}>What You're Buying</h2>
          <p>Novo Navis provides custom AI integration analysis reports for small businesses. These reports are generated by our proprietary Small Psychological Model and are designed to give you clear, practical guidance on how artificial intelligence tools may be applied to your business workflows.</p>
          <p>Reports are provided for informational purposes and do not constitute legal, financial, accounting, tax, or medical advice. For significant business, legal, financial, or operational decisions, please consult an appropriate licensed professional.</p>

          <h2 style={{color: '#c8a96e', fontSize: '1.2rem', marginTop: '2rem', marginBottom: '0.8rem'}}>Accuracy of Information</h2>
          <p>The quality of your Novo Navis report depends on the accuracy and completeness of the information you provide in your intake form. We cannot be responsible for reports that are inaccurate or incomplete due to inaccurate or incomplete information provided by the Client.</p>
          <p>Tool pricing, feature sets, and availability referenced in reports are current as of the date of report generation and are subject to change by third-party vendors. We recommend verifying all pricing and features directly with vendors before making purchasing decisions.</p>

          <h2 style={{color: '#c8a96e', fontSize: '1.2rem', marginTop: '2rem', marginBottom: '0.8rem'}}>Client Responsibility</h2>
          <p>You retain full and sole responsibility for any business decisions you make based on information provided in a Novo Navis report. Please independently verify all tool recommendations, pricing estimates, and ROI projections before implementing them. Where appropriate, consult licensed professionals — such as attorneys, accountants, financial advisors, or technology consultants — before making significant operational changes.</p>
          <p>Our reports are analytical tools to inform your decision making, not directives to be followed without independent evaluation. The suitability of any recommendation depends on factors specific to your business that may not be fully captured in your intake form responses.</p>

          <h2 style={{color: '#c8a96e', fontSize: '1.2rem', marginTop: '2rem', marginBottom: '0.8rem'}}>No Guarantee of Specific Results</h2>
          <p>Novo Navis makes no warranty, express or implied, that implementing the recommendations in any report will result in specific business outcomes, cost savings, revenue increases, or efficiency improvements. All ROI estimates, time savings projections, and financial calculations in reports are estimates based on industry data, not guarantees of actual results.</p>
          <p>Business results depend on numerous factors outside Novo Navis's control, including market conditions, staff adoption, implementation quality, vendor performance, and business-specific circumstances.</p>

          <h2 style={{color: '#c8a96e', fontSize: '1.2rem', marginTop: '2rem', marginBottom: '0.8rem'}}>Limitation of Liability</h2>
          <p>Novo Navis Aerospace Operations LLC, its officers, employees, agents, and representatives shall not be held liable for any direct, indirect, incidental, consequential, special, or exemplary damages arising from or related to your use of, reliance upon, or implementation of any information, recommendation, or analysis contained in a Novo Navis report.</p>
          <p>This includes losses arising from the implementation of AI tools recommended in a report, business decisions made in reliance on report findings, failure of recommended tools or strategies to produce expected results, costs incurred in implementation, lost revenue, lost profits, or business interruption of any kind.</p>
          <p>You agree to hold Novo Navis harmless from claims, damages, losses, liabilities, costs, and expenses arising from your use or implementation of information provided in a Novo Navis report.</p>

          <h2 style={{color: '#c8a96e', fontSize: '1.2rem', marginTop: '2rem', marginBottom: '0.8rem'}}>Intellectual Property</h2>
          <p>All reports are delivered to you for your personal business use. You may not resell, redistribute, publish, or commercially exploit any Novo Navis report without written permission from Novo Navis Aerospace Operations LLC. The underlying Small Psychological Model architecture, methodologies, and systems used to generate reports are proprietary intellectual property of Novo Navis Aerospace Operations LLC.</p>

          <h2 style={{color: '#c8a96e', fontSize: '1.2rem', marginTop: '2rem', marginBottom: '0.8rem'}}>Businesses We Cannot Serve</h2>
          <p>As a registered U.S. federal contractor, Novo Navis is required to decline service to certain categories of business. These restrictions apply only in specific situations and will not affect the vast majority of small business clients:</p>
          <p><strong style={{color: '#d0d8e8'}}>Cannabis and Marijuana Operations.</strong> Federal contracting rules prohibit us from conducting business with cultivation, distribution, sale, or dispensing operations involving cannabis or marijuana, regardless of applicable state or local legalization.</p>
          <p><strong style={{color: '#d0d8e8'}}>Businesses in Conflict with U.S. National Security.</strong> Because Novo Navis conducts active research under U.S. Department of Defense programs, we cannot provide services to any business whose operations, ownership, or intended use of our services would conflict with those responsibilities.</p>
          <p><strong style={{color: '#d0d8e8'}}>Other Discretionary Exclusions.</strong> We reserve the right to decline service to any business engaged in activities that conflict with local, state, federal, or international law.</p>
          <p>If we determine we cannot fulfill an order for any of the reasons above, you will receive a full and prompt refund. Submission of an order is not a guarantee of service.</p>

          <h2 style={{color: '#c8a96e', fontSize: '1.2rem', marginTop: '2rem', marginBottom: '0.8rem'}}>Governing Law</h2>
          <p>These Terms and Conditions are governed by the laws of the State of Arizona. Any disputes arising under these terms shall be subject to the exclusive jurisdiction of the courts of Maricopa County, Arizona.</p>

          <h2 style={{color: '#c8a96e', fontSize: '1.2rem', marginTop: '2rem', marginBottom: '0.8rem'}}>Changes to These Terms</h2>
          <p>Novo Navis reserves the right to update these Terms and Conditions at any time. Updated terms will be posted on this page with a revised effective date. Your continued use of our service after any changes constitutes acceptance of the updated terms.</p>

          <h2 style={{color: '#c8a96e', fontSize: '1.2rem', marginTop: '2rem', marginBottom: '0.8rem'}}>Contact Us</h2>
          <p>If you have any questions about these Terms and Conditions, please contact us:</p>
          <p>
            Novo Navis Aerospace Operations LLC<br />
            Sun City, Arizona 85351<br />
            Email: <a href="mailto:support@novonavis.com" style={{color: '#c8a96e'}}>support@novonavis.com</a><br />
            Phone: <a href="tel:6234289308" style={{color: '#c8a96e'}}>(623) 428-9308</a>
          </p>

        </div>

      </div>

      <footer>
        <p>© {new Date().getFullYear()} Novo Navis Aerospace Operations LLC · Fidelis Diligentia</p>
        <p style={{marginTop: '0.5rem'}}>
          <Link href="/blog">Blog</Link> &nbsp;·&nbsp;
          <Link href="/report">Get Your AI Blueprint</Link> &nbsp;·&nbsp;
          <Link href="/about">About</Link> &nbsp;·&nbsp;
          <Link href="/privacy">Privacy Policy</Link> &nbsp;·&nbsp;
          <Link href="/terms">Terms and Conditions</Link>
        </p>
      </footer>
    </>
  )
}