import Head from 'next/head'
import Link from 'next/link'

export default function Terms() {
  return (
    <>
      <Head>
        <title>Terms and Conditions | Novo Navis</title>
        <meta name="description" content="Novo Navis Terms and Conditions — please read before using our AI integration report service." />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <nav>
        <Link href="/" className="nav-logo">NOVO NAVIS</Link>
        <ul className="nav-links">
          <li><Link href="/">Home</Link></li>
          <li><Link href="/blog">Blog</Link></li>
          <li><Link href="/report">Get Your Report</Link></li>
          <li><Link href="/about">About</Link></li>
        </ul>
      </nav>

      <div className="article-page">

        <h1>Terms and Conditions</h1>
        <p style={{color: '#8a95aa', fontSize: '0.85rem', marginBottom: '2rem'}}>
          Effective Date: April 7, 2026 · Novo Navis Aerospace Operations LLC
        </p>

        <div className="article-body">

          <h2 style={{color: '#c8a96e', fontSize: '1.2rem', marginTop: '2rem', marginBottom: '0.8rem'}}>Agreement to Terms</h2>
          <p>By requesting, purchasing, or using any report or service provided by Novo Navis Aerospace Operations LLC ("Novo Navis," "we," "us," or "our"), you ("the Client," "you," or "your") agree to be bound by these Terms and Conditions. If you do not agree to these terms, do not submit a report request or complete a purchase.</p>

          <h2 style={{color: '#c8a96e', fontSize: '1.2rem', marginTop: '2rem', marginBottom: '0.8rem'}}>Nature of the Service</h2>
          <p>Novo Navis provides custom AI integration analysis reports for small businesses. These reports are generated by our proprietary Small Psychological Model and are intended to provide general informational guidance on how artificial intelligence tools may be applied to business workflows.</p>
          <p>All reports are provided for informational purposes only. The information contained in any Novo Navis report does not constitute legal advice, financial advice, accounting advice, tax advice, medical advice, or any other form of professional licensed advice. You should consult qualified professionals before making significant business, legal, financial, or operational decisions.</p>

          <h2 style={{color: '#c8a96e', fontSize: '1.2rem', marginTop: '2rem', marginBottom: '0.8rem'}}>Limitation of Liability and Hold Harmless</h2>
          <p>You acknowledge and agree that Novo Navis Aerospace Operations LLC, its officers, employees, agents, and representatives shall not be held liable for any direct, indirect, incidental, consequential, special, or exemplary damages arising from or related to your use of, reliance upon, or implementation of any information, recommendation, or analysis contained in a Novo Navis report.</p>
          <p>This includes but is not limited to losses arising from the implementation of AI tools recommended in a report, business decisions made in reliance on report findings, failure of recommended tools or strategies to produce expected results, costs incurred in implementing recommendations, lost revenue, lost profits, or business interruption of any kind.</p>
          <p>You agree to hold Novo Navis harmless from any and all claims, damages, losses, liabilities, costs, and expenses arising from your use or implementation of any information provided in a Novo Navis report.</p>

          <h2 style={{color: '#c8a96e', fontSize: '1.2rem', marginTop: '2rem', marginBottom: '0.8rem'}}>Client Responsibility</h2>
          <p>You retain full and sole responsibility for any business decisions made in connection with information provided in a Novo Navis report. You are responsible for independently verifying all tool recommendations, pricing estimates, and ROI projections before implementing them in your business. You are responsible for consulting appropriate licensed professionals — including attorneys, accountants, financial advisors, and technology consultants — before making significant operational changes.</p>
          <p>Novo Navis reports are analytical tools to inform your decision making, not directives to be followed without independent evaluation. The suitability of any recommendation depends on factors specific to your business that may not be fully captured in your intake form responses.</p>

          <h2 style={{color: '#c8a96e', fontSize: '1.2rem', marginTop: '2rem', marginBottom: '0.8rem'}}>No Guarantee of Results</h2>
          <p>Novo Navis makes no warranty, express or implied, that implementing the recommendations contained in any report will result in specific business outcomes, cost savings, revenue increases, efficiency improvements, or any other projected result. All ROI estimates, time savings projections, and financial calculations contained in reports are estimates based on industry data and are not guarantees of actual results.</p>
          <p>Business results depend on numerous factors outside Novo Navis's control including but not limited to market conditions, staff adoption, implementation quality, vendor performance, and business-specific circumstances.</p>

          <h2 style={{color: '#c8a96e', fontSize: '1.2rem', marginTop: '2rem', marginBottom: '0.8rem'}}>Accuracy of Information</h2>
          <p>The quality and accuracy of your Novo Navis report depends significantly on the accuracy and completeness of the information you provide in your intake form. Novo Navis is not responsible for inaccurate or incomplete reports resulting from inaccurate or incomplete information provided by the Client.</p>
          <p>Tool pricing, feature sets, and availability referenced in reports are current as of the date of report generation and are subject to change by third-party vendors. Novo Navis recommends verifying all pricing and features directly with vendors before making purchasing decisions.</p>

          <h2 style={{color: '#c8a96e', fontSize: '1.2rem', marginTop: '2rem', marginBottom: '0.8rem'}}>Intellectual Property</h2>
          <p>All reports generated by Novo Navis are delivered to you for your personal business use only. You may not resell, redistribute, publish, or commercially exploit any Novo Navis report without written permission from Novo Navis Aerospace Operations LLC. The underlying Small Psychological Model architecture, methodologies, and systems used to generate reports are proprietary intellectual property of Novo Navis Aerospace Operations LLC.</p>

          <h2 style={{color: '#c8a96e', fontSize: '1.2rem', marginTop: '2rem', marginBottom: '0.8rem'}}>Refund Policy</h2>
          <p>Novo Navis offers a full refund if your report does not deliver actionable AI integration recommendations specific to your business. Refund requests must be submitted to support@novonavis.com within 7 days of report delivery. Refunds are processed through Stripe and may take 5 to 10 business days to appear on your statement.</p>

          <h2 style={{color: '#c8a96e', fontSize: '1.2rem', marginTop: '2rem', marginBottom: '0.8rem'}}>Governing Law</h2>
          <p>These Terms and Conditions shall be governed by and construed in accordance with the laws of the State of Arizona. Any disputes arising under these terms shall be subject to the exclusive jurisdiction of the courts of Maricopa County, Arizona.</p>

          <h2 style={{color: '#c8a96e', fontSize: '1.2rem', marginTop: '2rem', marginBottom: '0.8rem'}}>Changes to These Terms</h2>
          <p>Novo Navis reserves the right to update these Terms and Conditions at any time. Updated terms will be posted on this page with a revised effective date. Your continued use of our service after any changes constitutes acceptance of the updated terms.</p>

          <h2 style={{color: '#c8a96e', fontSize: '1.2rem', marginTop: '2rem', marginBottom: '0.8rem'}}>Contact Us</h2>
          <p>If you have any questions about these Terms and Conditions, please contact us:</p>
          <p>
            Novo Navis Aerospace Operations LLC<br />
            Sun City, Arizona 85351<br />
            Email: <a href="mailto:support@novonavis.com" style={{color: '#c8a96e'}}>support@novonavis.com</a><br />
            Phone: <a href="tel:6234289308" style={{color: '#c8a96e'}}>(623) 428-9308</a>
          </p>

        </div>

      </div>

      <footer>
        <p>© {new Date().getFullYear()} Novo Navis Aerospace Operations LLC · Fidelis Diligentia</p>
        <p style={{marginTop: '0.5rem'}}>
          <Link href="/blog">Blog</Link> &nbsp;·&nbsp;
          <Link href="/report">Get Your Report</Link> &nbsp;·&nbsp;
          <Link href="/about">About</Link> &nbsp;·&nbsp;
          <Link href="/privacy">Privacy Policy</Link> &nbsp;·&nbsp;
          <Link href="/terms">Terms and Conditions</Link>
        </p>
      </footer>
    </>
  )
}